name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      uses: izumin5210/actions-go-crossbuild@master
      with:
        name: pubsubcli
        package: ./cmd/pubsubcli

    - uses: actions/upload-artifact@master
      with:
        name: pubsubcli
        path: dist
